# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentBasticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u8bbe\u5907\u540d\u79f0')),
                ('type', models.CharField(max_length=20, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
                ('modelType', models.CharField(max_length=20, verbose_name='\u8bbe\u5907\u578b\u53f7')),
                ('price', models.IntegerField(verbose_name='\u8bbe\u5907\u5355\u4ef7')),
                ('user', models.CharField(max_length=10, verbose_name='\u4f7f\u7528\u4eba')),
                ('position', models.CharField(max_length=20, verbose_name='\u6240\u5728\u4f4d\u7f6e')),
                ('purchasetime', models.DateField(verbose_name='\u8d2d\u4e70\u65f6\u95f4')),
                ('remark', models.CharField(max_length=50, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u57fa\u672c\u4fe1\u606f',
                'verbose_name_plural': '\u8bbe\u5907\u57fa\u672c\u4fe1\u606f\u8868',
            },
        ),
    ]
