# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentbasticinfo',
            name='remark',
            field=models.CharField(default='', max_length=50, verbose_name='\u5907\u6ce8'),
        ),
    ]
