# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fa', '0003_auto_20170209_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u4f4d\u7f6e')),
            ],
            options={
                'verbose_name': '\u4f4d\u7f6e',
                'verbose_name_plural': '\u4f4d\u7f6e\u8868',
            },
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'verbose_name': '\u8bbe\u5907\u7c7b\u578b', 'verbose_name_plural': '\u8bbe\u5907\u7c7b\u578b\u8868'},
        ),
        migrations.AlterField(
            model_name='equipmentbasticinfo',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fa.EquipmentPosition', verbose_name='\u6240\u5728\u4f4d\u7f6e'),
        ),
    ]
