# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fa', '0004_auto_20170209_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentposition',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='\u4f4d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='\u7c7b\u578b\u540d\u79f0'),
        ),
    ]
